// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACNpr45tXXr8SzyUV9wcr314Zx3GScNCI',
    appId: '1:348488256138:android:3f7087ffc96fb9a7dcbb73',
    messagingSenderId: '348488256138',
    projectId: 'prakpm-51b2f',
    storageBucket: 'prakpm-51b2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4O9MQP8jDvyQc2MhWqkHCbWVUW2k_AS0',
    appId: '1:348488256138:ios:245291d218f3e27adcbb73',
    messagingSenderId: '348488256138',
    projectId: 'prakpm-51b2f',
    storageBucket: 'prakpm-51b2f.firebasestorage.app',
    androidClientId: '348488256138-n26974np0pll4j8qq2pao8ollvvepi29.apps.googleusercontent.com',
    iosClientId: '348488256138-q8ueots4ufa3i6jh1b1emc9sq4448c7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

}